#*** Main Policy for nmeta - NFPS Load Test
#*** Written in YAML
#
tc_policies:
    # Traffic Classification Policies:
    'DDoS evaluation':
        comment: Policy for evaluating statistical DDoS classifier.
        rule_set: tc_ruleset_1
        port_set: all_access_ports
        mode: active
#
tc_rules:
    # Traffic Classification Rulesets and Rules
    tc_ruleset_1:
        - comment: DDoS Detection using Random Forest
          match_type: any
          conditions_list:
              - match_type: any
                statistical: "ml_ddos_random_forest"
          actions:
            set_qos: classifier_return
            set_desc: description="Detection of DDoS attack traffic."

#
identity:
    # Control how identity information is collected
    # This is a 1 for on and 0 for off but will later tie to set of
    # ports on which to run it
    #
    # Turn this on to collect ARP MAC address to IPv4 address mappings:
    arp: 0
    #
    # Turn this on to collect Link Layer Discovery Protocol information:
    lldp: 0
    #
    # Turn this on to collect DNS reply data matching services to IP addresses:
    dns: 0
    #
    # Turn this on to collect DHCP information about address allocations and
    # hostnames:
    dhcp: 0
#
qos_treatment:
    # Control Quality of Service (QoS) treatment mapping of
    #  names to output queue numbers:
    default_priority: 0
    constrained_bw: 1
    high_priority: 2
    low_priority: 3
#
port_sets:
    # Port Sets control what data plane ports policies and
    #  features are applied on:
    all_access_ports:
        - 'sw1-virtual':
            DPID: 1
            ports: 1
